[project]
name = "aoc_project"
version = "0.1.0"
description = "Advent of Code Project"
authors = [
    { name="Your Name", email="your.email@example.com" }
]
dependencies = []
requires-python = ">=3.9"

[build-system]
requires = ["uv>=0.1.0"]
build-backend = "uv"

[tool.uv]
lockfile = "uv.lock"
