[project]
name = "aoc_project"
version = "0.1.0"
description = "Advent of Code AI solving Project"
authors = [
    { name="Tamas Bodis", email="tamas.bodis@gmail.com" }
]
dependencies = []
requires-python = ">=3.12"

[build-system]
requires = ["uv>=0.5.24"]
build-backend = "uv"
